import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import cm


def generate_pdf_report(candidates: list, job_title: str, output_path: str) -> str:
    """Generate a professional PDF report of ranked candidates"""

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        topMargin=2*cm,
        bottomMargin=2*cm
    )
    styles = getSampleStyleSheet()
    story = []

    # ── Title ──
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        textColor=colors.HexColor("#4F46E5"),
        fontSize=22
    )
    story.append(Paragraph("TalentAI — Candidate Match Report", title_style))
    story.append(Spacer(1, 8))

    # ── Job info ──
    story.append(Paragraph(f"<b>Job Position:</b> {job_title}", styles["Normal"]))
    story.append(Paragraph(
        f"<b>Generated:</b> {datetime.now().strftime('%d %B %Y, %I:%M %p')}",
        styles["Normal"]
    ))
    story.append(Paragraph(f"<b>Total Candidates Ranked:</b> {len(candidates)}", styles["Normal"]))
    story.append(Spacer(1, 20))

    # ── Candidates Table ──
    table_data = [["Rank", "Candidate", "Email", "ATS Score", "Match Score"]]
    for i, c in enumerate(candidates, 1):
        table_data.append([
            f"#{i}",
            (c.get("candidate_name") or "Unknown")[:28],
            (c.get("email") or "—")[:32],
            f"{c.get('ats_score', 0):.0f}%",
            f"{c.get('match_score', 0):.1f}%"
        ])

    table = Table(table_data, colWidths=[1.4*cm, 5*cm, 6*cm, 2.4*cm, 2.6*cm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4F46E5")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F3F4F6")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ("ALIGN", (3, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(table)
    story.append(Spacer(1, 24))

    # ── Top Candidate Highlight ──
    if candidates:
        top = candidates[0]
        story.append(Paragraph("Top Recommended Candidate", styles["Heading2"]))
        story.append(Paragraph(f"<b>Name:</b> {top.get('candidate_name', 'Unknown')}", styles["Normal"]))
        story.append(Paragraph(f"<b>Email:</b> {top.get('email', '—')}", styles["Normal"]))
        skills = ", ".join(top.get("skills", [])[:10]) or "Not listed"
        story.append(Paragraph(f"<b>Key Skills:</b> {skills}", styles["Normal"]))
        story.append(Paragraph(
            f"<b>Scores:</b> Match {top.get('match_score', 0):.1f}% | ATS {top.get('ats_score', 0):.0f}%",
            styles["Normal"]
        ))

    # ── Footer ──
    story.append(Spacer(1, 30))
    footer_style = ParagraphStyle("Footer", parent=styles["Normal"],
                                  textColor=colors.grey, fontSize=8)
    story.append(Paragraph(
        "Generated by TalentAI Recruiter — AI-Powered Recruitment Platform",
        footer_style
    ))

    doc.build(story)
    return output_path

def generate_contacts_pdf(candidates: list, output_path: str) -> str:
    """Generate a contact directory PDF of all candidates"""

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        topMargin=2*cm,
        bottomMargin=2*cm
    )
    styles = getSampleStyleSheet()
    story = []

    # ── Title ──
    title_style = ParagraphStyle(
        "ContactTitle",
        parent=styles["Title"],
        textColor=colors.HexColor("#4F46E5"),
        fontSize=22
    )
    story.append(Paragraph("TalentAI — Candidate Contact Directory", title_style))
    story.append(Spacer(1, 8))

    story.append(Paragraph(
        f"<b>Generated:</b> {datetime.now().strftime('%d %B %Y, %I:%M %p')}",
        styles["Normal"]
    ))
    story.append(Paragraph(f"<b>Total Candidates:</b> {len(candidates)}", styles["Normal"]))
    story.append(Spacer(1, 20))

    # ── Contacts Table ──
    table_data = [["#", "Candidate Name", "Email", "Phone"]]
    for i, c in enumerate(candidates, 1):
        table_data.append([
            str(i),
            (c.get("candidate_name") or "Unknown")[:30],
            (c.get("email") or "—")[:38],
            (c.get("phone") or "—")[:18]
        ])

    table = Table(table_data, colWidths=[1.2*cm, 5.5*cm, 6.8*cm, 3.5*cm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4F46E5")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F3F4F6")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
    ]))
    story.append(table)

    # ── Footer ──
    story.append(Spacer(1, 30))
    footer_style = ParagraphStyle("Footer", parent=styles["Normal"],
                                  textColor=colors.grey, fontSize=8)
    story.append(Paragraph(
        "Generated by TalentAI Recruiter — AI-Powered Recruitment Platform",
        footer_style
    ))

    doc.build(story)
    return output_path